# 异常处理  
## 异常捕获与处理
### Throwable,Error,Exception
 - java中异常结构有三种Throwable,Error,Exception,Exception表示网络故障,文件损坏,设备错误,用户输入非法
 - Error 运行环境出错,例如JVM内存资源耗尽
### try_catch  
 - 错时，虚拟机会实例化这个错误的实例, 并讲程序运行到错误这里的过程设置到该实例中, 有了完成的错误信息后,虚拟机会将异常抛出
 - 没有异常发生,略过catch
    ```java
    public class Exception_try_catch {
	   public static void main(String[] args) {
		    System.out.println("程序开始了");

		    try {

			   String str = null;
			     /*
    			 - 出错时，虚拟机会实例化这个错误的实例
    			 - 并讲程序运行到错误这里的过程设置到该实例中
    			 - 有了完成的错误信息后,虚拟机会将异常抛出
			     */
			   System.out.println(str.length());
			   //try中出错代码下面代码不会运行
			   System.out.println("!!!");
		    }catch(NullPointerException e) {
			   System.out.println("\n出现了空指针\n");
		    }

		    System.out.println("程序结束了");
	   }
    }
    ```
### 多个catch
  - 每个try语句块可以伴随多个catch语句,用于处理不同类型的异常
  - 顺序由上至下,有继承关系则子类到父类
  - 最后添加catch(Exception e) 用于未知异常
    ```java
    public class Exception_try_catch {
	public static void main(String[] args) {
		System.out.println("程序开始了");

		try {

			String str = "";
			/*
			 * 出错时，虚拟机会实例化这个错误的实例
			 * 并讲程序运行到错误这里的过程设置到该实例中
			 * 有了完成的错误信息后,虚拟机会将异常抛出
			 */
			System.out.println(str.length());
			System.out.println(str.charAt(0));
			//try中出错代码下面代码不会运行
			System.out.println("!!!");
		}catch(NullPointerException e) {
			System.out.println("\n出现了空指针\n");
		}catch (StringIndexOutOfBoundsException e) {
			System.out.println("下标越界");
		}catch (Exception e) {
			System.out.println("未知异常");
		}

		System.out.println("程序结束了");
	}
    }

    ```
### finally
  - finally语句为异常处理提供平一个统一的出口,使得控制流程转到其他部分以前,能够对程序的状态作统一管理
  - 无论try所指定的程序块是否抛出异常,finally所指定的代码都要被执行
  - 通常在finally语句中可以进行资源的释放工作,入关闭打开的文件,删除临时文件等  
   `finally {
			System.out.println("finally代码运行");
		}`
### throws 抛出异常
 - 不希望直接处理方法中的异常，而希望用这个他的方法同意处理，可以用throw 关键字来声明这个方法将抛出异常
 - 通常方法中throw异常就要在方法上使用throws声明该类异常的抛出.只有RuntimeException及其子类型异常在抛出是无需在方法上使用throws声明
 - 当调用一个含有throws异常抛出声明的方法时,编译器必须要求处理该异常,否则编译不通过,而处理手段有两种:
   1. 使用try_catch 捕获并处理
   2. 继续在当前方法上使用throws将该异常声明继续向外抛出
   - throw
   ```java
   public void setAge(int age) {
		if(age<0||age>100) {
			throw new RuntimeException("年龄不合法");
		}
		this.age = age;
	}
   ```
   - throws
    ```java
    public void setAge(int age) throws Exception {
		if(age<0||age>100) {
			throw new Exception("年龄不合法");
		}
		this.age = age;
	}```
### 重写方法时的throws
 - 如果使用继承时,在父类别的某个方法上宣告了throws某些异常,而在子类别中重新定义该方法时
   - 你可以
     - 不处理异常(重新定义是不设定throws)
     - 可仅throws父类别声明的部分异常
     - 可throws父类方法中抛出异常的子类异常  -- 例如 FileNotFoundException是IOException 的子类异常
   - 不可以
     - throws出额外的异常   例如 不是父类异常的 RuntimeException
     - throws父类方法中抛出异常的父类异常 IOException 的 父类异常Exception
    ```java
    public class Exception_throws {
	      public void dosome() throws IOException, AWTException {
	       }
    }

    class son1 extends Exception_throws { // 仅抛出部分异常
	    public void dosome() throws IOException {
	    }
    }

    class son2 extends Exception_throws { // 抛出父类方法中抛出异常的子类型异常
	    public void dosome() throws FileNotFoundException {
	    }
    }

    class son3 extends Exception_throws { // 不抛出异常
	    public void dosome() {
	    }
    }
    ```
## Java异常API

### RuntimeException
 - Java异常分为 可检测异常 和 非检测异常 (RuntimeException)
   - 可检测异常:不捕获这个异常,编译器通不过,不允许编译
   - 非检测异常: 产生这种异常,不一定要采取适当操作,编译器不会检查是否已经解决了这样一个异常

### 常见RuntimeException
  - IllegalArgumentException 向方法传递一个不合法不正确的参数
  - NullPointerException 空指针异常
  - ArrayIndexOutOfBoundsException 超出数组范围
  - NumberFormatException 字符串转换格式异常

## Exception 常用API
### printStackTrace
 - Throwable中定义一个方法可以输出错误信息,用来跟踪异常事件发生时执行堆栈的内容
   - void printStackTrace()
     ```java
     try {
			String str = null;
			System.out.println(str.length());
		} catch (Exception e) {
			e.printStackTrace();  //  java.lang.NullPointerException
		}
     ```
### getMessage  
 - Throwable 中定义了一个方法可以得到有关异常事件的信息，该方法定义为
   - String getMessage()
     ```java
     try {
			String str = "a";
			System.out.println(Integer.parseInt(str));
		} catch (Exception e) {
			e.printStackTrace(); // java.lang.NumberFormatException: For input string: "a"
			System.out.println(e.getMessage()); // For input string: "a"
		}
     ```
### getCause
  - 检索导致异常的原因，获取该异常出现的原因
    - Throwable getCause()
### 自定义异常
  - 创建自定义异常
    ```java
    class [自定义异常类名] extends Exception{
      ...
    }
    ```
    - 例
    ```java
    public class IllegalAgeException extends Exception{

	private static final long serialVersionUID = 1L;

	public IllegalAgeException() {
		super();
	}

	public IllegalAgeException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
		super(message, cause, enableSuppression, writableStackTrace);
	}

	public IllegalAgeException(String message, Throwable cause) {
		super(message, cause);
	}

	public IllegalAgeException(String message) {
		super(message);
	}

	public IllegalAgeException(Throwable cause) {
		super(cause);
	}
    }

    ```
    ```java
    public class Person {
	private int age;

	public int getAge() {
		return age;
	}

	public void setAge(int age) throws IllegalAgeException {
		if(age<0||age>100) {
			throw new IllegalAgeException("年龄不合法");
		}
		this.age = age;
	}
    }
    ```

    ```java
    Person person = new Person();
		try {
			person.setAge(120);
		} catch (IllegalAgeException e) {
			e.printStackTrace();  // day08.IllegalAgeException: 年龄不合法
		}
    ```
